project = 'python-bale-bot'
copyright = '2022, Kian Ahmadian'
author = 'Kian Ahmadian'
release = '[]'
extensions = []
templates_path = ['_templates']
exclude_patterns = []
html_theme = 'alabaster'
html_static_path = ['_static']
