from .inputfile import InputFile
from .photosize import PhotoSize
from .basefile import BaseFile
from .document import Document
from .voice import Voice
from .audio import Audio
from .contact import Contact
from .location import Location
from .video import Video
from .animation import Animation
